title: OPC Docs
description: Documentation for the Oakton Programming Club
theme: just-the-docs

url: https://oakpr.github.io
color_scheme: dark
exclude:
  - test

callouts:
  note:
    title: Note
    color: grey-lt
  warning:
    title: Warning
    color: yellow